# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0736679238d5347f49fe2476bd55ae021ef77aaded1095ebf8da527917e8efbc135b0986e5c9dfacb74039ae63e495e3d607202af44a6d85e17b48b390bc2cd3

test:
  secret_key_base: c4991459461f6685e0d1d3e0264ff9752f01b7ad0fdc415c4a553b59e39276cba92fca622b243d1fa756a08a9a6b0e5536fafc2c3326021fed1d0a6138f68ae4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
