# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58466c86af516c02110d52d5cd4bc661c45e2786a27fc4246afd7ae068c9d908a4406c7cfcf9095bb5d3cba57df380327b132886aa6bdef599c99fb1181a82fa

test:
  secret_key_base: 0573042c8f5690a845a99990c6a9be71c547c5b18f68146f505ab0acf92f4e4273fd8aca26f04d69fcac96faccdfbf03f6af54f797b740a12e87a97801521257

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
